COMP: Update Swig interface files to use "slicer_itk" namespace
This commit ensures the type checks associated with "sitk.SetImageFromArray()"
and "sitk.GetMemoryViewFromImage()" functions do not report errors like
the following:

  Traceback (most recent call last):
    File "<console>", line 1, in <module>
    File "/path/to/lib/Python/Lib/site-packages/SimpleITK/extra.py", line 269, in GetArrayFromImage
      array_view = GetArrayViewFromImage(image)
    File "/path/to/lib/Python/Lib/site-packages/SimpleITK/extra.py", line 255, in GetArrayViewFromImage
      image_memory_view = _GetMemoryViewFromImage(image)
  TypeError: in method 'GetByteArrayFromImage', argument needs to be of type 'sitk::Image *'

It also fixes the warnings reported when "SimpleITKPYTHON_wrap.cxx"
is generated using the custom command implemented in "CMake/sitkUseSWIG.cmake":

  /path/to/SimpleITK/Wrapping/Python/Python.i:83:
  Warning 303: %extend defined for an undeclared class itk::simple::ProcessObject.

  /path/to/SimpleITK/Wrapping/Python/sitkTransform.i:134:
  Warning 303: %extend defined for an undeclared class itk::simple::Transform.

  /path/to/SimpleITK/Wrapping/Python/sitkImage.i:965:
  Warning 303: %extend defined for an undeclared class itk::simple::Image.

  /path/to/SimpleITK/Code/Common/include/sitkPixelIDValues.h:125:
  Warning 509: Overloaded method slicer_itk::simple::GetPixelIDValueAsString(slicer_itk::simple::PixelIDValueEnum) effectively ignored,

  /path/to/SimpleITK/Code/Common/include/sitkPixelIDValues.h:124:
  Warning 509: as it is shadowed by slicer_itk::simple::GetPixelIDValueAsString(slicer_itk::simple::PixelIDValueType).

See https://github.com/Slicer/Slicer/issues/6598