COMP: Revert namespace changes in "sitkPathType.i" to fix build issues
This commit partially reverts commit aee26c3c (COMP: Update remaining Swig
interface files to use "slicer_itk" namespace) to address build warnings and
errors encountered while building the "SimpleITK_PYTHON" target.

Example warning:

```
C:\path\to\SimpleITK\Code\IO\include\sitkImageViewer.h(123): warning 490: Fragment '<type_traits>' not found.
```

Example errors:

```
C:\path\to\SimpleITK-build\SimpleITK-build\Wrapping\Python\SimpleITKPYTHON_wrap.cxx(65016,23):
error C3861: 'SWIG_PyUnicode_AsUTF8AndSize': identifier not found
C:\path\to\SimpleITK-build\SimpleITK-build\Wrapping\Python\SimpleITKPYTHON_wrap.cxx(65020,16):
error C3861: 'SWIG_sitk_PathType_isPathInstance': identifier not found
```